### PR TITLE
Add custom InspectorFrontendHost with copy support

### LINKED ISSUE #30: Copying requests as cURL does not work
Apparently the clipboard is not enabled in hosted mode.

screen shot 2015-02-13 at 7 51 17 pm

Any idea why this is?

### PR DESCRIPTION
**Pull request by gingermusketeer**
Fixes #30

### CODE REVIEW

**Comment by gingermusketeer** [comment]
Not necessarily ready for merge. I just wanted to get a conversation going

Looking at the InspectorFrontendHostStub methods i think we will need to expand this custom InspectorFrontEndHost to add support for workspaces etc.


Note this PR will not carry over whenever the devtools are upgraded. How do we want to handle injecting this into the devtools code?

**Comment by auchenberg** [comment]
Yeah. I've been thinking about that too. It's great to see that the Chrome team has implemented an interface in the ``InspectorFrontendHostStub``, which makes it super easy for us to map the functionality. 

But I don't like changing ``module.json``, as it makes pulling changes in Devtools much harder. Since ``InspectorFrontendHostStub``  is exposing itself on the global ``window`` object, we could theoretically inject the relevant files via a proxy or something?

**Comment by gingermusketeer** [comment]
Yea. Having that stub is really nice. It was pretty clear what was needed to get this working in its current form.

Did you have something in mind for the proxy? I think it is reading the files directly from the file system.

I was wondering if the simplest way would be to add a script that creates a symlink to the file in the right place and modifies the module.json. This could get run as part of the devtools upgrade

**Comment by auchenberg** [comment]
Your right. It's probably the easiest to write a script that modifies ``module.json`` instead of re-inventing the injection mechanism. I already generate a few files in https://github.com/auchenberg/chrome-devtools-app/blob/master/scripts/build_generated_scripts.js, so we can just add another?

I know that the node-inspector team is doing a similar thing.

**Comment by gingermusketeer** [comment]
@auchenberg I have made the changes. Let me know if there is anything else you want me to tweak

**Comment by auchenberg** [comment]
Looking great :+1:  Thanks!

**Pull request merged**
