### PR TITLE
Upgrade devtools

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by auchenberg** [comment]
I'm currently not in front of a computer, but have you testes that
"everything" is working? Last time I updated DevTools a bunch of files had
changed and I see 404s in the console as a fee files had to be generated.

/k

**Comment by gingermusketeer** [comment]
I connected it to chrome and tried a bunch of things. Everything worked that i tried. Cannot remember if i checked the console. I will check it and report back

**Comment by gingermusketeer** [comment]
I have done an extensive test and everything is working. The only errors coming up in the console are from the stubbed host methods.

**Comment by auchenberg** [comment]
Cool, let's get it in, and start implementing the functionality in the frontend host :)

**Pull request merged**
